name: LaTex Compile and Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Compile CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            cv_en/cv_en.tex
            cv_cn/cv_cn.tex
          work_in_root_file_dir: true
          latexmk_use_xelatex: true

      - name: Setup repository
        run: |
          ls -l ${GITHUB_WORKSPACE}
          ls -l ${GITHUB_WORKSPACE}/cv_cn
          ls -l ${GITHUB_WORKSPACE}/cv_en

          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git clone https://github.com/beiyuouo/beiyuouo.github.io homepage

          cp ${GITHUB_WORKSPACE}/cv_cn/cv_cn.pdf homepage/pdf/cv_cn.pdf
          cp ${GITHUB_WORKSPACE}/cv_en/cv_en.pdf homepage/pdf/cv_en.pdf

          cd homepage && git add . && git commit -m "Update CV"

          git status

      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/beiyuouo/beiyuouo.github.io.git"
          source_branch: "master"
          destination_repo: "https://github.com/beiyuouo/beiyuouo.github.io.git"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.PUBLISH_KEY }} # optional
