name: LaTex Compile and Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            cv_en/cv_en.tex
            cv_cn/cv_cn.tex
          work_in_root_file_dir: true
          latexmk_use_xelatex: true

      - name: Push to main repository
        run: |
          ls -l ${GITHUB_WORKSPACE}
          ls -l ${GITHUB_WORKSPACE}/cv_cn
          ls -l ${GITHUB_WORKSPACE}/cv_en
